// Anatomy data for the Rumah Gadang house.

export const CATEGORIES = [
  { id: 'base',     label: { en: 'Foundation', id: 'Fondasi' }, local: 'Dasar',   color: '#9a948a' },
  { id: 'struct',   label: { en: 'Structure', id: 'Struktur' },  local: 'Struktur', color: '#b27a45' },
  { id: 'walls',    label: { en: 'Walls', id: 'Dinding' },      local: 'Dindiang', color: '#dcab52' },
  { id: 'roof',     label: { en: 'Roof', id: 'Atap' },       local: 'Atap',    color: '#cf5b3f' },
  { id: 'interior', label: { en: 'Interior', id: 'Interior' },   local: 'Dalam',   color: '#b3674a' },
];

export const COMPONENTS = [
  {
    id: 'batu_sandi', cat: 'base', name: 'Batu Sandi', alias: 'Batu tapakan', en: { en: 'Stone footings', id: 'Batu sandi' },
    explode: [0, 0, 0], anchor: [8.4, 0.3, 3.6],
    desc: { en: 'Flat stones set on the ground under every column. The posts stand on them rather than being sunk into the earth.', id: 'Batu pipih yang diletakkan di atas tanah di bawah setiap tiang. Tiang berdiri di atasnya, tidak ditanam ke dalam tanah.' },
    fn: { en: 'Keep the timber off damp soil. West Sumatra is highly seismic, and a frame resting loosely on stones can rock and settle in an earthquake instead of breaking.', id: 'Menjauhkan kayu dari tanah yang lembap. Sumatera Barat sangat rawan gempa, dan rangka yang bertumpu longgar di atas batu dapat bergoyang lalu kembali mapan saat gempa, alih-alih patah.' },
    meaning: { en: 'A foundation that yields rather than resists, much like the adat saying that the house should bend with nature, not against it.', id: 'Fondasi yang mengalah alih-alih melawan, sejalan dengan petuah adat bahwa rumah hendaknya mengikuti alam, bukan menentangnya.' },
    specs: [{ en: '32 stones', id: '32 batu' }, { en: 'Columns rest, not buried', id: 'Tiang bertumpu, tidak ditanam' }],
  },
  {
    id: 'tiang', cat: 'struct', name: 'Tiang', alias: 'Tiang tuo', en: { en: 'Columns', id: 'Tiang' },
    explode: [0, 1.4, 0], anchor: [-6, 1.2, 3.6], focusDir: [0.4, 0.15, 1],
    desc: { en: 'A forest of round timber columns carries the whole house. The first one raised, the tiang tuo, is treated as the principal column.', id: 'Hutan tiang kayu bulat memikul seluruh rumah. Tiang yang pertama didirikan, tiang tuo, dianggap sebagai tiang utama.' },
    fn: { en: 'Lift the floor about two metres off the ground and carry the roof. The length of a rumah gadang is counted in ruang, the bays between columns.', id: 'Mengangkat lantai sekitar dua meter dari tanah dan memikul atap. Panjang rumah gadang dihitung dalam ruang, yaitu jarak di antara tiang-tiang.' },
    meaning: { en: 'Raising the tiang tuo is a communal event for the whole kaum (clan), who share the work of building the house.', id: 'Mendirikan tiang tuo adalah peristiwa bersama bagi seluruh kaum, yang bergotong royong membangun rumah.' },
    specs: [{ en: '32 columns', id: '32 tiang' }, { en: '7 ruang long', id: 'Panjang 7 ruang' }, { en: 'Round timber', id: 'Kayu bulat' }],
  },
  {
    id: 'rasuak_paran', cat: 'struct', name: 'Rasuak & Paran', alias: 'Rasuk, paran', en: { en: 'Tie beams & top beams', id: 'Rasuak & paran' },
    explode: [0, 2.6, 0], anchor: [0, 1.75, 3.6],
    desc: { en: 'Rasuak are beams that pass through the columns below the floor; paran run across the column heads under the roof.', id: 'Rasuak adalah balok yang menembus tiang-tiang di bawah lantai; paran membentang di atas kepala tiang di bawah atap.' },
    fn: { en: 'Lock the columns into a rigid grid with timber pegs (pasak) instead of nails, and spread the roof load onto every post.', id: 'Mengunci tiang-tiang menjadi jaringan yang kaku dengan pasak kayu, bukan paku, dan membagi beban atap ke setiap tiang.' },
    meaning: { en: 'Like the members of a clan, no single beam stands alone. The frame is strong because every piece is tied to the others.', id: 'Seperti anggota sebuah kaum, tidak ada balok yang berdiri sendiri. Rangkanya kuat karena setiap bagian terikat pada yang lain.' },
    specs: [{ en: 'Pegged joints', id: 'Sambungan pasak' }, { en: 'No nails', id: 'Tanpa paku' }],
  },
  {
    id: 'lantai', cat: 'struct', name: 'Lantai', alias: 'Lantai papan', en: { en: 'Raised floor', id: 'Lantai panggung' },
    explode: [0, 3.4, 0], anchor: [-3, 2.05, 0],
    desc: { en: 'A timber floor of long boards laid over the rasuak, about two metres above the ground.', id: 'Lantai dari papan-papan panjang yang dipasang di atas rasuak, sekitar dua meter di atas tanah.' },
    fn: { en: 'Keeps the living space dry, cool and safe from animals. The space underneath (kolong) is used for storage, tools and livestock.', id: 'Menjaga ruang hunian tetap kering, sejuk, dan aman dari binatang. Ruang di bawahnya (kolong) dipakai untuk menyimpan barang, perkakas, dan ternak.' },
    meaning: { en: 'The long open hall above is where the family gathers and where ceremonies are held.', id: 'Ruang panjang yang terbuka di atasnya adalah tempat keluarga berkumpul dan upacara diadakan.' },
    specs: ['17.5 × 7.9 m', { en: 'Floor +2.0 m', id: 'Lantai +2,0 m' }],
  },
  {
    id: 'tangga', cat: 'struct', name: 'Tangga', alias: 'Tangga & surambi', en: { en: 'Entrance stair & porch', id: 'Tangga & beranda masuk' },
    explode: [0, 3.4, 3.2], anchor: [0.9, 1.2, 7.0], focusDir: [0.8, 0.3, 1],
    desc: { en: 'The main entrance is reached by a timber stair up to a small covered porch in the middle of the front wall.', id: 'Pintu masuk utama dicapai melalui tangga kayu menuju beranda kecil beratap di tengah dinding depan.' },
    fn: { en: 'Brings visitors up to floor level under shelter from the rain. The porch has its own gonjong roof.', id: 'Membawa tamu naik ke lantai rumah dengan terlindung dari hujan. Beranda ini memiliki atap gonjong sendiri.' },
    meaning: { en: 'Traditionally a jar of water stood by the stairs so that visitors could wash their feet before entering.', id: 'Secara tradisi, sebuah tempayan air diletakkan di dekat tangga agar tamu dapat membasuh kaki sebelum masuk.' },
    specs: [{ en: '8 steps', id: '8 anak tangga' }, { en: 'Own gonjong roof', id: 'Atap gonjong sendiri' }],
  },
  {
    id: 'dinding_ukiran', cat: 'walls', name: 'Dinding Ukiran', alias: 'Dindiang baukia', en: { en: 'Carved walls', id: 'Dinding berukir' },
    explode: [0, 4.6, 0], anchor: [-7.8, 3.3, 4.2],
    desc: { en: 'The front and side walls are made of timber panels carved and painted in red, black and gold, with motifs taken from nature such as kaluak paku (fern tendrils) and itiak pulang patang (ducks returning home at dusk).', id: 'Dinding depan dan samping terbuat dari panel kayu yang diukir dan diwarnai merah, hitam, dan emas, dengan motif dari alam seperti kaluak paku (pucuk pakis) dan itiak pulang patang (itik pulang petang).' },
    fn: { en: 'Enclose the hall and form the public face of the house. The walls lean outward as they rise, following the flare of the roof.', id: 'Menutup ruang dan menjadi wajah rumah di depan umum. Dinding condong ke luar makin ke atas, mengikuti lengkung atap.' },
    meaning: { en: 'The carvings reflect the Minangkabau philosophy alam takambang jadi guru: nature, as it unfolds, is the teacher.', id: 'Ukirannya mencerminkan falsafah Minangkabau alam takambang jadi guru: alam yang terbentang adalah guru.' },
    specs: [{ en: 'Leans out 0.4 m', id: 'Condong 0,4 m ke luar' }, { en: 'Painted carving', id: 'Ukiran berwarna' }],
  },
  {
    id: 'dinding_sasak', cat: 'walls', name: 'Dinding Sasak', alias: 'Dindiang sasak', en: { en: 'Woven bamboo back wall', id: 'Dinding belakang anyaman bambu' },
    explode: [0, 4.6, -3.2], anchor: [3, 3.3, -4.2], focusDir: [0.3, 0.2, -1],
    desc: { en: 'The back wall is made of split bamboo woven in a twill pattern, lighter and plainer than the carved front.', id: 'Dinding belakang terbuat dari bilah bambu yang dianyam bermotif kepang, lebih ringan dan polos daripada bagian depan yang berukir.' },
    fn: { en: 'Lets air pass through while keeping out the view. Private sleeping rooms (biliak) for the married daughters line the back of the house.', id: 'Mengalirkan udara sambil menahan pandangan dari luar. Kamar-kamar tidur (biliak) bagi anak perempuan yang sudah menikah berjajar di bagian belakang rumah.' },
    meaning: { en: 'The contrast is deliberate: the carved front faces the public, the plain back shelters private family life.', id: 'Perbedaannya disengaja: bagian depan yang berukir menghadap umum, bagian belakang yang polos menaungi kehidupan pribadi keluarga.' },
    specs: [{ en: 'Split bamboo', id: 'Bilah bambu' }, { en: 'Twill weave', id: 'Anyaman kepang' }],
  },
  {
    id: 'jendela', cat: 'walls', name: 'Pintu & Jendela', alias: 'Pintu, jandela', en: { en: 'Door & windows', id: 'Pintu & jendela' },
    explode: [0, 4.6, 2.4], anchor: [-4.8, 3.3, 4.4],
    desc: { en: 'A row of windows with painted shutters runs along the front and ends; the main door opens from the entrance porch.', id: 'Deretan jendela dengan daun jendela berwarna berjajar di bagian depan dan kedua ujung; pintu utama dibuka dari beranda masuk.' },
    fn: { en: 'Bring daylight and breeze into the long central hall.', id: 'Memasukkan cahaya dan angin ke ruang tengah yang panjang.' },
    meaning: { en: 'Windows along the facade let the family watch over the courtyard and the rangkiang in front of the house.', id: 'Jendela di sepanjang fasad memungkinkan keluarga mengawasi halaman dan rangkiang di depan rumah.' },
    specs: [{ en: '10 windows', id: '10 jendela' }, { en: '1 main door', id: '1 pintu utama' }],
  },
  {
    id: 'biliak', cat: 'interior', name: 'Biliak', alias: 'Bilik', en: { en: 'Sleeping rooms of the daughters', id: 'Kamar tidur anak perempuan' },
    explode: [0, 3.0, -2.6], anchor: [-4.8, 3.6, -1.1], focusDir: [0.3, 0.55, 1],
    desc: { en: 'A row of small rooms along the back of the long hall, one in each bay between the columns, each with its own door.', id: 'Deretan kamar kecil di sepanjang bagian belakang ruang panjang, satu di setiap ruang di antara tiang, masing-masing dengan pintunya sendiri.' },
    fn: { en: 'Each married daughter of the house has her own biliak, where she lives with her husband and young children.', id: 'Setiap anak perempuan yang sudah menikah memiliki biliaknya sendiri, tempat ia tinggal bersama suami dan anak-anaknya yang masih kecil.' },
    meaning: { en: 'The heart of the matrilineal house: the house belongs to its women, and husbands come to live in their wives’ rooms.', id: 'Jantung rumah matrilineal: rumah ini milik kaum perempuannya, dan para suami datang untuk tinggal di kamar istri mereka.' },
    specs: [{ en: '7 rooms', id: '7 kamar' }, { en: 'One per ruang', id: 'Satu per ruang' }],
  },
  {
    id: 'singok', cat: 'walls', name: 'Singok', alias: 'Singkok', en: { en: 'Carved gable ends', id: 'Singok berukir' },
    explode: [0, 6.2, 0], anchor: [9.15, 5.4, 0], focusDir: [1, 0.2, 0.35],
    desc: { en: 'The triangular gable walls under the upswept ends of the roof, usually carved and painted like the front.', id: 'Dinding segitiga di bawah ujung atap yang melengkung naik, biasanya diukir dan diwarnai seperti bagian depan.' },
    fn: { en: 'Close the space between the walls and the rising curve of the roof.', id: 'Menutup ruang antara dinding dan lengkung atap yang naik.' },
    meaning: { en: 'Seen from afar, the carved gables and horns make each house recognisable to its clan.', id: 'Dilihat dari jauh, singok berukir dan gonjong membuat setiap rumah dikenali oleh kaumnya.' },
    specs: [{ en: '3 gables', id: '3 singok' }, { en: 'Painted carving', id: 'Ukiran berwarna' }],
  },
  {
    id: 'kasau', cat: 'roof', name: 'Kasau', alias: 'Kasau & bubuangan', en: { en: 'Rafters & ridge beam', id: 'Kasau & bubungan' },
    explode: [0, 7.4, 0], anchor: [2.5, 6.4, 2.6],
    desc: { en: 'Rafters follow the sweep of the roof down from a sagging ridge beam (bubuangan) that curves upward at each end.', id: 'Kasau mengikuti lengkung atap turun dari balok bubungan (bubuangan) yang melendut dan melengkung naik di kedua ujungnya.' },
    fn: { en: 'Give the roof its saddle shape and carry the heavy thatch.', id: 'Memberi atap bentuk pelananya dan memikul ijuk yang berat.' },
    meaning: { en: 'The curve is built into the frame itself. The roof is not bent afterwards; its shape is designed from the start.', id: 'Lengkungnya dibentuk oleh rangka itu sendiri. Atap tidak dibengkokkan belakangan; bentuknya sudah dirancang sejak awal.' },
    specs: [{ en: '{kasau} rafters', id: '{kasau} kasau' }, { en: 'Curved ridge beams', id: 'Bubungan melengkung' }],
  },
  {
    id: 'atap_ijuak', cat: 'roof', name: 'Atap Ijuak', alias: 'Atap ijuk', en: { en: 'Sugar-palm fibre roof', id: 'Atap ijuk' }, roof: true,
    explode: [0, 9.4, 0], anchor: [0, 7.4, 2.2],
    desc: { en: 'The roof is thatched with thick layers of black ijuk, the fibre of the sugar palm. Many houses today use corrugated zinc (seng) instead.', id: 'Atapnya dari lapisan tebal ijuk hitam, serat pohon aren. Kini banyak rumah menggantinya dengan seng.' },
    fn: { en: 'Ijuk sheds heavy rain, resists rot and insulates the hall from the tropical sun. The steep slopes carry water away quickly.', id: 'Ijuk mengalirkan hujan lebat, tahan busuk, dan melindungi ruang dari terik matahari tropis. Kemiringan yang curam mengalirkan air dengan cepat.' },
    meaning: { en: 'A well-kept ijuk roof can last for decades, a sign of a family that looks after its heritage.', id: 'Atap ijuk yang terawat dapat bertahan puluhan tahun, tanda keluarga yang menjaga warisannya.' },
    specs: [{ en: 'Ijuk thatch', id: 'Atap ijuk' }, { en: '4 roof sections', id: '4 bagian atap' }],
  },
  {
    id: 'gonjong', cat: 'roof', name: 'Gonjong', alias: 'Rumah bagonjong', en: { en: 'Horn-shaped roof peaks', id: 'Puncak atap berbentuk tanduk' }, roof: true,
    explode: [0, 10.6, 0], anchor: [6.8, 12.1, 0], focusDir: [0.8, 0.35, 1],
    desc: { en: 'The upswept, pointed ends of the roof, capped with metal finials. This house has five, one on the entrance porch.', id: 'Ujung atap yang melengkung naik dan runcing, bermahkota logam. Rumah ini memiliki lima gonjong, salah satunya di beranda masuk.' },
    fn: { en: 'The rising tips throw rainwater clear of the walls and give the roof its tall, airy inner space.', id: 'Ujung yang menjulang melontarkan air hujan menjauhi dinding dan memberi atap ruang dalam yang tinggi dan lapang.' },
    meaning: { en: 'Often likened to buffalo horns, recalling the legend of the buffalo contest that gave the Minangkabau (menang kerbau, “the winning buffalo”) their name. Others see the hull of a ship.', id: 'Sering diibaratkan tanduk kerbau, mengingatkan pada legenda adu kerbau yang memberi nama Minangkabau (menang kerbau). Ada pula yang melihatnya sebagai lambung kapal.' },
    specs: ['5 gonjong', { en: 'Metal finials', id: 'Puncak logam' }],
  },
];
