// Anatomy data for the pendapa's parts: naming, explode vector, label anchor and learning notes.

export const CATEGORIES = [
  { id: 'base',   label: { en: 'Foundation', id: 'Fondasi' }, local: 'Dasar',  color: '#9a948a' },
  { id: 'column', label: { en: 'Columns', id: 'Tiang' },    local: 'Saka',   color: '#b27a45' },
  { id: 'frame',  label: { en: 'Frame', id: 'Rangka' },      local: 'Rangka', color: '#dcab52' },
  { id: 'roof',   label: { en: 'Roof', id: 'Atap' },       local: 'Atap',   color: '#cf5b3f' },
];

export const COMPONENTS = [
  {
    id: 'bebatur', cat: 'base', name: 'Bebatur', alias: 'Undhak-undhakan', en: { en: 'Raised platform & steps', id: 'Lantai tinggi & tangga' },
    explode: [0, 0.0, 0], anchor: [0, 0.35, 7.9],
    desc: { en: 'The pendapa stands on a raised plinth of stone or brick, finished with floor tiles. Guests climb a short flight of steps from the open courtyard (latar) to reach it.', id: 'Pendapa berdiri di atas bebatur batu atau bata yang ditinggikan dan berlapis tegel. Tamu menaiki beberapa anak tangga dari halaman terbuka (latar) untuk mencapainya.' },
    fn: { en: 'Lifts the timber frame clear of rain splash and ground damp, and marks out the formal floor of the hall.', id: 'Mengangkat rangka kayu dari percikan hujan dan kelembapan tanah, serta menandai lantai resmi balairung.' },
    meaning: { en: 'Height expresses hierarchy. Stepping up onto the pendapa means leaving the everyday ground for a more refined, ordered space.', id: 'Ketinggian mencerminkan hierarki. Naik ke pendapa berarti meninggalkan tanah keseharian menuju ruang yang lebih halus dan tertata.' },
    specs: ['16.6 × 14.6 m', { en: 'Floor +0.60 m', id: 'Lantai +0,60 m' }, { en: '2 flights of steps', id: '2 deret anak tangga' }],
  },
  {
    id: 'umpak', cat: 'base', name: 'Umpak', alias: 'Ompak', en: { en: 'Stone column bases', id: 'Alas tiang dari batu' }, interp: true,
    explode: [0, 1.3, 0], anchor: [5.2, 0.85, 4.4],
    desc: { en: 'A truncated pyramid of andesite set under every column. The faces are often carved with lotus (padma) or foliage motifs. The post rests on top, held by a short tenon (purus), and is never buried.', id: 'Batu andesit berbentuk limas terpancung di bawah setiap tiang. Sisi-sisinya sering diukir motif teratai (padma) atau dedaunan. Tiang bertumpu di atasnya, ditahan oleh purus pendek, dan tidak pernah ditanam.' },
    fn: { en: 'Keeps the teak off the damp ground and out of reach of termites. The columns rest on the stones rather than being buried, so the frame can be taken apart and moved.', id: 'Menjauhkan kayu jati dari tanah yang lembap dan dari jangkauan rayap. Tiang bertumpu di atas batu, tidak ditanam, sehingga rangkanya bisa dibongkar dan dipindahkan.' },
    meaning: { en: 'The stone links the earth with the wooden body of the house. The padma motif suggests purity rising out of the ground.', id: 'Batu ini menghubungkan bumi dengan tubuh kayu rumah. Motif padma mengisyaratkan kesucian yang tumbuh dari tanah.' },
    specs: [{ en: '36 bases', id: '36 umpak' }, { en: 'Andesite', id: 'Andesit' }, { en: '0.35–0.40 m high', id: 'Tinggi 0,35–0,40 m' }],
  },
  {
    id: 'saka_guru', cat: 'column', name: 'Saka Guru', alias: 'Soko guru', en: { en: 'Four master columns', id: 'Empat tiang utama' },
    explode: [0, 2.6, 0], anchor: [2.2, 4.2, 1.9], focusDir: [0.9, 0.25, 1],
    desc: { en: 'The four tallest columns at the heart of the joglo, cut from the best teak (jati). Together they carry the tumpang sari and the whole steep upper roof.', id: 'Empat tiang tertinggi di jantung joglo, dibuat dari kayu jati terbaik. Bersama-sama keempatnya memikul tumpang sari dan seluruh atap atas yang curam.' },
    fn: { en: 'The main load path. Almost all of the brunjung roof’s weight comes down through these four posts.', id: 'Jalur beban utama. Hampir seluruh berat atap brunjung disalurkan turun melalui keempat tiang ini.' },
    meaning: { en: 'They stand for the four cardinal directions (keblat papat) around a sacred centre (pancer). Raising them is traditionally accompanied by offerings and prayer.', id: 'Keempatnya melambangkan empat arah mata angin (keblat papat) di sekeliling pusat yang sakral (pancer). Pendiriannya secara tradisi disertai sesaji dan doa.' },
    specs: [{ en: '4 columns', id: '4 tiang' }, '32 × 32 cm', { en: '5.2 m tall', id: 'Tinggi 5,2 m' }],
  },
  {
    id: 'sunduk_kili', cat: 'frame', name: 'Sunduk & Kili', alias: 'Sunduk kili', en: { en: 'Through-beams & wedges', id: 'Balok tembus & pasak baji' }, interp: true,
    explode: [0, 3.7, 0], anchor: [0, 5.25, 1.9], focusDir: [0.6, 0.1, 1],
    desc: { en: 'Sunduk are horizontal beams that pass through mortises cut in the saka guru. Kili are timber wedges driven in beside them to lock the joint tight.', id: 'Sunduk adalah balok mendatar yang menembus lubang pada saka guru. Kili adalah baji kayu yang dimasukkan di sampingnya untuk mengunci sambungan dengan rapat.' },
    fn: { en: 'Braces the four saka guru into a rigid cage against sway, with no nails or metal fasteners. The same knock-down joinery means a joglo can be taken apart and rebuilt somewhere else.', id: 'Mengunci keempat saka guru menjadi sangkar kaku yang tahan goyangan, tanpa paku atau pengikat logam. Sambungan bongkar-pasang ini pula yang membuat joglo bisa dibongkar dan didirikan kembali di tempat lain.' },
    meaning: { en: 'It reflects the Javanese ideal of harmony (rukun): parts held together by fit and balance, not force.', id: 'Ini mencerminkan cita-cita Jawa tentang kerukunan (rukun): bagian-bagian yang bersatu karena kecocokan dan keseimbangan, bukan paksaan.' },
    specs: ['4 sunduk', { en: '8 kili wedges', id: '8 baji kili' }, { en: 'Mortise & wedge', id: 'Lubang & baji' }],
  },
  {
    id: 'santen', cat: 'frame', name: 'Santen', alias: 'Sesanten', en: { en: 'Posts between sunduk and pengeret', id: 'Tiang antara sunduk dan pengeret' },
    explode: [0, 3.7, 0], anchor: [2.2, 5.6, 0], focusDir: [1, 0.1, 0.5],
    desc: { en: 'Short timber pieces that join each cross sunduk to the pengeret above it.', id: 'Potongan kayu pendek yang menghubungkan setiap sunduk melintang dengan pengeret di atasnya.' },
    fn: { en: 'Fix the distance between sunduk and pengeret so the two work together as one stiffer frame.', id: 'Menetapkan jarak antara sunduk dan pengeret sehingga keduanya bekerja sebagai satu rangka yang lebih kaku.' },
    meaning: { en: 'The name probably comes from samanten, “only this much”: the gap between sunduk and pengeret is always the same.', id: 'Namanya kemungkinan berasal dari samanten, “hanya segini”: jarak antara sunduk dan pengeret selalu sama.' },
    specs: [{ en: '2 santen', id: '2 santen' }],
  },
  {
    id: 'saka_penanggap', cat: 'column', name: 'Saka Penanggap', alias: 'Soko penanggap', en: { en: 'Second-ring columns', id: 'Tiang lingkar kedua' }, interp: true,
    explode: [0, 2.6, 0], anchor: [-5.2, 3.0, 4.4],
    desc: { en: 'Twelve columns in a ring around the saka guru. They are shorter and slimmer, and carry the middle roof tier (atap penanggap).', id: 'Dua belas tiang yang melingkari saka guru. Tiang-tiang ini lebih pendek dan ramping, dan memikul susun atap tengah (atap penanggap).' },
    fn: { en: 'Support the lower ends of the penanggap rafters and frame the central space of the hall.', id: 'Menopang ujung bawah usuk penanggap dan membingkai ruang tengah balairung.' },
    meaning: { en: 'Like attendants around the four masters, they show how the house is ordered in rings from a sacred centre out to the everyday edge.', id: 'Seperti para pengiring di sekeliling empat tiang utama, tiang-tiang ini menunjukkan bagaimana rumah ditata berlapis-lapis, dari pusat yang sakral hingga tepi yang sehari-hari.' },
    specs: [{ en: '12 columns', id: '12 tiang' }, '26 × 26 cm', { en: '3.85 m tall', id: 'Tinggi 3,85 m' }],
  },
  {
    id: 'saka_penitih', cat: 'column', name: 'Saka Penitih', alias: 'Saka emper', en: { en: 'Outer veranda columns', id: 'Tiang emper luar' },
    explode: [0, 2.6, 0], anchor: [7.8, 2.2, 6.8],
    desc: { en: 'Twenty short columns on the outer edge of the pendapa. They support the lowest and widest roof tier.', id: 'Dua puluh tiang pendek di tepi luar pendapa. Tiang-tiang ini menopang susun atap terbawah dan terlebar.' },
    fn: { en: 'Carry the deep eaves that shade the floor and keep driving rain off the inner columns.', id: 'Memikul tritisan lebar yang meneduhi lantai dan melindungi tiang-tiang dalam dari tempias hujan.' },
    meaning: { en: 'The threshold between the open courtyard and the covered hall, where guests are first received.', id: 'Ambang antara halaman terbuka dan balairung beratap, tempat tamu pertama kali disambut.' },
    specs: [{ en: '20 columns', id: '20 tiang' }, '22 × 22 cm', { en: '2.65 m tall', id: 'Tinggi 2,65 m' }],
  },
  {
    id: 'blandar', cat: 'frame', name: 'Blandar', alias: 'Balok blandar', en: { en: 'Lengthwise ring beams', id: 'Balok keliling memanjang' },
    explode: [0, 4.7, 0], anchor: [0, 4.95, 4.4],
    desc: { en: 'Beams running along the length of the building, resting on the column heads with tenon joints. With the pengeret across the ends, they close a frame over each ring of columns.', id: 'Balok yang membentang memanjang bangunan, bertumpu di kepala tiang dengan sambungan purus. Bersama pengeret yang melintang di ujung-ujungnya, blandar menutup rangka di atas setiap lingkar tiang.' },
    fn: { en: 'Gather the roof loads along the long sides and pass them down to the columns.', id: 'Mengumpulkan beban atap di sisi panjang dan menyalurkannya ke tiang.' },
    meaning: { en: 'The blandar–pengeret frame over the saka guru encloses the pamidhangan, the most honoured zone under the roof.', id: 'Rangka blandar–pengeret di atas saka guru melingkupi pamidhangan, area paling terhormat di bawah atap.' },
    specs: [{ en: '6 beams', id: '6 balok' }, { en: 'Tenon joints', id: 'Sambungan purus' }, { en: 'Teak', id: 'Jati' }],
  },
  {
    id: 'pengeret', cat: 'frame', name: 'Pengeret', alias: 'Pangeret', en: { en: 'Cross beams', id: 'Balok melintang' },
    explode: [0, 4.7, 0], anchor: [5.2, 4.95, 0], focusDir: [1, 0.3, 0.4],
    desc: { en: 'Beams running across the building, from front to back, at right angles to the blandar. Two short pengeret laid over the top of the frame, above the ceiling, carry the ander.', id: 'Balok yang membentang melintang bangunan, dari depan ke belakang, tegak lurus terhadap blandar. Dua pengeret pendek yang diletakkan di atas rangka, di atas langit-langit, memikul ander.' },
    fn: { en: 'Tie each ring of columns across its width, and carry the ander that hold up the molo.', id: 'Mengikat setiap lingkar tiang pada lebarnya, dan memikul ander yang menyangga molo.' },
    meaning: { en: 'Every member of the frame has its own name in the Javanese carpentry tradition, so a builder can describe a house beam by beam.', id: 'Setiap batang rangka memiliki nama sendiri dalam tradisi pertukangan kayu Jawa, sehingga tukang dapat menjelaskan rumah balok demi balok.' }, interp: true,
    specs: [{ en: '8 beams', id: '8 balok' }, { en: 'Across the blandar', id: 'Melintang blandar' }],
  },
  {
    id: 'tumpang_sari', cat: 'frame', name: 'Tumpang Sari', alias: 'Tumpangsari', en: { en: 'Stepped beam stack', id: 'Susunan balok bertingkat' },
    explode: [0, 5.9, 0], anchor: [0, 6.95, 2.6], focusDir: [0.5, -0.55, 1],
    desc: { en: 'Frames of beams stacked on top of the saka guru. Each course steps further out than the one below, forming an upside-down stepped pyramid.', id: 'Rangka-rangka balok yang ditumpuk di atas saka guru. Setiap susun menjorok lebih jauh daripada susun di bawahnya, membentuk piramida berundak yang terbalik.' },
    fn: { en: 'Cantilevers outward to hold the foot of the steep brunjung rafters, gathering a large roof onto just four columns.', id: 'Menjorok ke luar untuk menahan kaki usuk brunjung yang curam, sehingga atap yang besar dapat bertumpu hanya pada empat tiang.' },
    meaning: { en: 'The most richly carved and painted part of the house, often gilded (prada) with lung-lungan tendril motifs. The number of courses is traditionally odd and reflects the owner’s rank.', id: 'Bagian rumah yang paling kaya ukiran dan warna, sering diprada dengan motif sulur lung-lungan. Secara tradisi jumlah susunnya ganjil dan mencerminkan kedudukan pemiliknya.' },
    specs: [{ en: '5 courses', id: '5 susun' }, { en: 'Stepped outward', id: 'Berundak ke luar' }, { en: 'Carved & gilded', id: 'Diukir & diprada' }],
  },
  {
    id: 'dadha_peksi', cat: 'frame', name: 'Dhadha Peksi', alias: 'Dada peksi', en: { en: '“Bird’s chest” beam', id: 'Balok “dada burung”' }, interp: true,
    explode: [0, 6.9, 0], anchor: [1.3, 6.6, 0], focusDir: [0.5, -1, 0.9],
    desc: { en: 'A heavy beam across the middle of the tumpang sari, parallel to the blandar, usually carved and painted. Its name means “bird’s chest” in Javanese.', id: 'Balok besar yang melintang di tengah tumpang sari, sejajar dengan blandar, biasanya diukir dan diwarnai. Dalam bahasa Jawa namanya berarti “dada burung”.' },
    fn: { en: 'Stiffens the central frame and splits the space over the saka guru into two halves.', id: 'Memperkaku rangka tengah dan membagi ruang di atas saka guru menjadi dua bagian.' },
    meaning: { en: 'The name can be read as a bird’s breast: strong, central and protective, sheltering the heart of the house.', id: 'Namanya dapat dibaca sebagai dada burung: kokoh, di tengah, dan melindungi, menaungi jantung rumah.' },
    specs: [{ en: '1 beam', id: '1 balok' }, { en: '4.9 m span', id: 'Bentang 4,9 m' }, { en: 'Painted trim', id: 'Bingkai berwarna' }],
  },
  {
    id: 'uleng', cat: 'frame', name: 'Uleng', alias: 'Plafon', en: { en: 'Recessed stepped ceiling', id: 'Langit-langit berundak' }, interp: true,
    explode: [0, 8.3, 0], anchor: [0, 7.95, 0], focusDir: [0.35, -1, 0.7],
    desc: { en: 'The recessed ceiling above the tumpang sari, made of frames stepping inward and upward. You see it when you look straight up from the centre of the pendapa.', id: 'Langit-langit yang menjorok ke atas tumpang sari, tersusun dari rangka yang berundak ke dalam dan ke atas. Terlihat saat kita menengadah tepat dari tengah pendapa.' },
    fn: { en: 'Closes off the middle of the tall roof and draws the eye upward.', id: 'Menutup bagian tengah atap yang tinggi dan menarik pandangan ke atas.' },
    meaning: { en: 'Its depth marks the sacred centre of the hall, the highest and most honoured place under the roof.', id: 'Kedalamannya menandai pusat sakral balairung, tempat tertinggi dan paling terhormat di bawah atap.' },
    specs: [{ en: '4 inward steps', id: '4 undakan ke dalam' }, { en: 'Ceiling board', id: 'Papan langit-langit' }, { en: 'Painted panels', id: 'Panel berwarna' }],
  },
  {
    id: 'lambang_gantung', cat: 'frame', name: 'Lambang Gantung', alias: 'Saka benthung', en: { en: 'Hanging roof-tier posts', id: 'Tiang gantung antarsusun atap' },
    explode: [0, 7.7, 0], anchor: [-3.25, 6.5, 2.95],
    desc: { en: 'Short hanging posts (saka benthung) and light ring beams at the foot of the steep brunjung. They carry the top of the gentler penanggap roof, leaving a gap between the two tiers.', id: 'Tiang gantung pendek (saka benthung) dan balok keliling ringan di kaki brunjung yang curam. Keduanya menopang ujung atas atap penanggap yang lebih landai, menyisakan celah di antara kedua susun.' },
    fn: { en: 'Joins two roof tiers of different pitch. The gap between them lets warm air out and daylight in.', id: 'Menyambung dua susun atap dengan kemiringan berbeda. Celah di antaranya mengeluarkan udara panas dan memasukkan cahaya.' },
    meaning: { en: 'Joglo are classified by how their roof tiers meet. In the lambang gantung type the tiers are separated by a gap like this one; in the lambangsari type a beam joins them directly, with no gap.', id: 'Joglo digolongkan menurut cara susun atapnya bertemu. Pada tipe lambang gantung, kedua susun dipisahkan oleh celah seperti ini; pada tipe lambangsari, sebuah balok menyambungnya langsung tanpa celah.' },
    specs: [{ en: '2 rings + posts', id: '2 cincin + tiang' }, { en: '~0.7 m vent gap', id: 'Celah ventilasi ~0,7 m' }],
  },
  {
    id: 'usuk', cat: 'roof', name: 'Usuk & Reng', alias: 'Usuk, reng', en: { en: 'Rafters & battens', id: 'Usuk & reng' }, interp: true,
    explode: [0, 9.7, 0], anchor: [4.4, 5.55, 3.9],
    desc: { en: 'Usuk (rafters) run from the upper frames down to the eaves. Thin reng (battens) laid across them hold the clay tiles. In many joglo the corner rafters fan out radially (usuk peniyung) like the ribs of an umbrella; this model simplifies them to parallel rafters.', id: 'Usuk membentang dari rangka atas hingga ke tritisan. Reng yang tipis dipasang melintang di atasnya untuk menahan genteng. Pada banyak joglo, usuk di sudut menyebar seperti jari-jari payung (usuk peniyung); model ini menyederhanakannya menjadi usuk sejajar.' },
    fn: { en: 'Pass the weight of the tiles to the beams and hips, and set the pitch of each roof tier.', id: 'Menyalurkan berat genteng ke balok dan jurai, serta menentukan kemiringan setiap susun atap.' },
    meaning: { en: 'Many slender members sharing one load, a picture of gotong royong, the Javanese practice of mutual help.', id: 'Banyak batang ramping yang berbagi satu beban, gambaran gotong royong, tradisi saling membantu dalam masyarakat Jawa.' },
    specs: [{ en: '{rafters} rafters', id: '{rafters} usuk' }, { en: '{battens} battens', id: '{battens} reng' }],
  },
  {
    id: 'dudur', cat: 'roof', name: 'Dudur', alias: 'Jurai', en: { en: 'Hip rafters', id: 'Jurai' },
    explode: [0, 10.9, 0], anchor: [7.35, 4.15, 6.45],
    desc: { en: 'Heavy diagonal rafters along the four corners of each roof tier, where two slopes meet.', id: 'Kasau diagonal yang besar di keempat sudut setiap susun atap, tempat dua bidang atap bertemu.' },
    fn: { en: 'Carry the ends of the shorter corner rafters and hold the hipped shape of each tier.', id: 'Menahan ujung usuk sudut yang lebih pendek dan menjaga bentuk limas setiap susun.' },
    meaning: { en: 'They give the joglo its sweeping pyramid silhouette.', id: 'Jurai memberi joglo siluet piramidanya yang khas.' },
    specs: [{ en: '12 hips', id: '12 jurai' }, { en: '3 roof tiers', id: '3 susun atap' }],
  },
  {
    id: 'molo', cat: 'roof', name: 'Molo', alias: 'Suwunan', en: { en: 'Ridge beam', id: 'Balok bubungan' },
    explode: [0, 10.9, 0], anchor: [0, 10.8, 0],
    desc: { en: 'The ridge beam at the very top of the brunjung, where the rafters and hips meet.', id: 'Balok bubungan di puncak brunjung, tempat usuk dan jurai bertemu.' },
    fn: { en: 'Ties together the tops of the brunjung rafters and dudur.', id: 'Mengikat ujung atas usuk brunjung dan dudur.' },
    meaning: { en: 'Seen as the head of the house. Lifting it into place is celebrated with the munggah molo ceremony, often with rice, bananas and cloth hung from the beam.', id: 'Dianggap sebagai kepala rumah. Pemasangannya dirayakan dengan upacara munggah molo, sering dengan padi, pisang, dan kain yang digantungkan pada balok.' },
    specs: [{ en: '2.1 m long', id: 'Panjang 2,1 m' }, { en: 'Highest timber', id: 'Kayu tertinggi' }],
  },
  {
    id: 'ander', cat: 'roof', name: 'Ander', alias: 'Ander', en: { en: 'Posts under the ridge', id: 'Tiang penyangga bubungan' },
    explode: [0, 9.6, 0], anchor: [0.75, 9.4, 0], focusDir: [0.6, 0.1, 1],
    desc: { en: 'Upright posts that hold up the molo. Here two ander stand on short pengeret over the top of the frame, hidden above the ceiling, and are joined to the molo with tenons.', id: 'Tiang tegak yang menyangga molo. Di sini dua ander berdiri di atas pengeret pendek di puncak rangka, tersembunyi di atas langit-langit, dan disambung ke molo dengan purus.' },
    fn: { en: 'Carry the ridge beam, so the top of the steep brunjung does not rest on the hip rafters alone.', id: 'Memikul balok bubungan, sehingga puncak brunjung yang curam tidak hanya bertumpu pada jurai.' },
    meaning: { en: 'Ander are found in every type of Javanese roof. How they stand inside a joglo varies; this placement is our reconstruction.', id: 'Ander ditemukan pada semua jenis atap Jawa. Cara ander berdiri di dalam joglo beragam; penempatan ini adalah rekonstruksi kami.' },
    specs: [{ en: '2 posts', id: '2 tiang' }, { en: 'Tenon joints', id: 'Sambungan purus' }],
  },
  {
    id: 'atap_brunjung', cat: 'roof', name: 'Atap Brunjung', alias: 'Brunjung', en: { en: 'Upper roof', id: 'Atap atas' }, interp: true,
    explode: [0, 14.4, 0], anchor: [0, 9.2, 1.4], roof: true,
    desc: { en: 'The tall, steep central roof over the saka guru. It is the defining joglo silhouette, with a short ridge and very steep hipped ends.', id: 'Atap tengah yang tinggi dan curam di atas saka guru. Inilah siluet khas joglo, dengan bubungan pendek dan sisi limas yang sangat curam.' },
    fn: { en: 'Sheds heavy tropical rain quickly, and its tall inner volume lets warm air rise away from people below.', id: 'Mengalirkan hujan tropis yang lebat dengan cepat, dan ruang dalamnya yang tinggi membuat udara panas naik menjauh dari orang di bawahnya.' },
    meaning: { en: 'A roof like a mountain (gunungan) rising over the sacred centre, joining earth and sky.', id: 'Atap bagaikan gunung (gunungan) yang menjulang di atas pusat sakral, menyatukan bumi dan langit.' },
    specs: [{ en: '≈52–57° pitch', id: 'Kemiringan ≈52–57°' }, { en: 'Ridge +11.0 m', id: 'Bubungan +11,0 m' }, { en: 'Clay tiles', id: 'Genteng tanah liat' }],
  },
  {
    id: 'atap_penanggap', cat: 'roof', name: 'Atap Penanggap', alias: 'Penanggap', en: { en: 'Middle roof tier', id: 'Susun atap tengah' },
    explode: [0, 13.1, 0], anchor: [0, 5.55, 4.3], roof: true,
    desc: { en: 'The second roof tier around the brunjung, at a gentler pitch, resting on the saka penanggap.', id: 'Susun atap kedua di sekeliling brunjung, dengan kemiringan lebih landai, bertumpu pada saka penanggap.' },
    fn: { en: 'Widens the covered area and protects the inner frame, while the gap above it vents the roof.', id: 'Memperluas area beratap dan melindungi rangka dalam, sementara celah di atasnya menjadi ventilasi atap.' },
    meaning: { en: 'The change in pitch between tiers gives the joglo its layered, stepped look.', id: 'Perbedaan kemiringan antarsusun memberi joglo tampilan yang berlapis dan berundak.' },
    specs: [{ en: '≈34° pitch', id: 'Kemiringan ≈34°' }, { en: 'Clay tiles', id: 'Genteng tanah liat' }],
  },
  {
    id: 'atap_penitih', cat: 'roof', name: 'Atap Penitih', alias: 'Emper', en: { en: 'Lower veranda roof', id: 'Atap emper bawah' },
    explode: [0, 12.1, 0], anchor: [0, 4.2, 6.4], roof: true,
    desc: { en: 'The lowest and widest roof tier, at a shallow pitch, overhanging the platform on every side.', id: 'Susun atap terbawah dan terlebar, dengan kemiringan landai, menjorok melewati lantai di semua sisi.' },
    fn: { en: 'Deep eaves keep sun and slanting rain off the floor and the inner timber.', id: 'Tritisan yang lebar melindungi lantai dan kayu di dalam dari terik matahari dan tempias hujan.' },
    meaning: { en: 'Shelters the edge of the hall where the courtyard and the house meet.', id: 'Menaungi tepi balairung, tempat halaman dan rumah bertemu.' },
    specs: [{ en: '≈20° pitch', id: 'Kemiringan ≈20°' }, { en: '0.7 m overhang', id: 'Tritisan 0,7 m' }, { en: 'Clay tiles', id: 'Genteng tanah liat' }],
  },
  {
    id: 'mustaka', cat: 'roof', name: 'Wuwungan & Mustaka', alias: 'Bubungan', en: { en: 'Ridge caps & crowns', id: 'Wuwung & mahkota' },
    explode: [0, 15.8, 0], anchor: [0.8, 11.9, 0],
    desc: { en: 'Ridge and hip capping tiles (wuwung) that seal the joints between slopes, finished at the ridge ends with ornamental terracotta crowns.', id: 'Genteng penutup bubungan dan jurai (wuwung) yang menutup sambungan antarbidang atap, diakhiri mahkota hias dari terakota di kedua ujung bubungan.' },
    fn: { en: 'Keeps rain out of the ridge and hip joints, the weakest points of a tiled roof.', id: 'Mencegah air hujan masuk ke sambungan bubungan dan jurai, titik terlemah atap genteng.' },
    meaning: { en: 'The crown is the crowning point of the house. Ridge ornaments were often symbols of protection and prosperity.', id: 'Mahkota adalah titik puncak rumah. Hiasan bubungan kerap menjadi lambang perlindungan dan kemakmuran.' },
    specs: [{ en: '2 crowns', id: '2 mahkota' }, { en: 'Ridge + 12 hip caps', id: 'Bubungan + 12 tutup jurai' }, { en: 'Terracotta', id: 'Terakota' }],
  },
];
