// Anatomy data for the pendapa's parts: naming, explode vector, label anchor and learning notes.

export const CATEGORIES = [
  { id: 'base',   label: 'Foundation', local: 'Dasar',  color: '#9a948a' },
  { id: 'column', label: 'Columns',    local: 'Saka',   color: '#b27a45' },
  { id: 'frame',  label: 'Frame',      local: 'Rangka', color: '#dcab52' },
  { id: 'roof',   label: 'Roof',       local: 'Atap',   color: '#cf5b3f' },
];

export const COMPONENTS = [
  {
    id: 'bebatur', cat: 'base', name: 'Bebatur', alias: 'Undhak-undhakan', en: 'Raised platform & steps',
    explode: [0, 0.0, 0], anchor: [0, 0.35, 7.9],
    desc: 'The pendapa stands on a raised plinth of stone or brick, finished with floor tiles. Guests climb a short flight of steps from the open courtyard (latar) to reach it.',
    fn: 'Lifts the timber frame clear of rain splash and ground damp, and marks out the formal floor of the hall.',
    meaning: 'Height expresses hierarchy. Stepping up onto the pendapa means leaving the everyday ground for a more refined, ordered space.',
    specs: ['16.6 × 14.6 m', 'Floor +0.60 m', '2 flights of steps'],
  },
  {
    id: 'umpak', cat: 'base', name: 'Umpak', alias: 'Ompak', en: 'Stone column bases', interp: true,
    explode: [0, 1.3, 0], anchor: [5.2, 0.85, 4.4],
    desc: 'A truncated pyramid of andesite set under every column. The faces are often carved with lotus (padma) or foliage motifs. The post rests on top, held by a short tenon (purus), and is never buried.',
    fn: 'Keeps the teak off the damp ground and out of reach of termites. The columns rest on the stones rather than being buried, so the frame can be taken apart and moved.',
    meaning: 'The stone links the earth with the wooden body of the house. The padma motif suggests purity rising out of the ground.',
    specs: ['36 bases', 'Andesite', '0.35–0.40 m high'],
  },
  {
    id: 'saka_guru', cat: 'column', name: 'Saka Guru', alias: 'Soko guru', en: 'Four master columns',
    explode: [0, 2.6, 0], anchor: [2.2, 4.2, 1.9], focusDir: [0.9, 0.25, 1],
    desc: 'The four tallest columns at the heart of the joglo, cut from the best teak (jati). Together they carry the tumpang sari and the whole steep upper roof.',
    fn: 'The main load path. Almost all of the brunjung roof’s weight comes down through these four posts.',
    meaning: 'They stand for the four cardinal directions (keblat papat) around a sacred centre (pancer). Raising them is traditionally accompanied by offerings and prayer.',
    specs: ['4 columns', '32 × 32 cm', '5.2 m tall'],
  },
  {
    id: 'sunduk_kili', cat: 'frame', name: 'Sunduk & Kili', alias: 'Sunduk kili', en: 'Through-beams & wedges', interp: true,
    explode: [0, 3.7, 0], anchor: [0, 5.25, 1.9], focusDir: [0.6, 0.1, 1],
    desc: 'Sunduk are horizontal beams that pass through mortises cut in the saka guru. Kili are timber wedges driven in beside them to lock the joint tight.',
    fn: 'Braces the four saka guru into a rigid cage against sway, with no nails or metal fasteners. The same knock-down joinery means a joglo can be taken apart and rebuilt somewhere else.',
    meaning: 'It reflects the Javanese ideal of harmony (rukun): parts held together by fit and balance, not force.',
    specs: ['4 sunduk', '8 kili wedges', 'Mortise & wedge'],
  },
  {
    id: 'saka_penanggap', cat: 'column', name: 'Saka Penanggap', alias: 'Soko penanggap', en: 'Second-ring columns', interp: true,
    explode: [0, 2.6, 0], anchor: [-5.2, 3.0, 4.4],
    desc: 'Twelve columns in a ring around the saka guru. They are shorter and slimmer, and carry the middle roof tier (atap penanggap).',
    fn: 'Support the lower ends of the penanggap rafters and frame the central space of the hall.',
    meaning: 'Like attendants around the four masters, they show how the house is ordered in rings from a sacred centre out to the everyday edge.',
    specs: ['12 columns', '26 × 26 cm', '3.85 m tall'],
  },
  {
    id: 'saka_penitih', cat: 'column', name: 'Saka Penitih', alias: 'Saka emper', en: 'Outer veranda columns',
    explode: [0, 2.6, 0], anchor: [7.8, 2.2, 6.8],
    desc: 'Twenty short columns on the outer edge of the pendapa. They support the lowest and widest roof tier.',
    fn: 'Carry the deep eaves that shade the floor and keep driving rain off the inner columns.',
    meaning: 'The threshold between the open courtyard and the covered hall, where guests are first received.',
    specs: ['20 columns', '22 × 22 cm', '2.65 m tall'],
  },
  {
    id: 'blandar', cat: 'frame', name: 'Blandar & Pengeret', alias: 'Balok blandar', en: 'Ring beams',
    explode: [0, 4.7, 0], anchor: [0, 4.95, 4.4],
    desc: 'Blandar run along the length of the building and pengeret run across it. Resting on the column heads with tenon joints, they form a closed frame for each ring of columns.',
    fn: 'Gather the roof loads and pass them down to the columns, and tie each ring of columns together.',
    meaning: 'The blandar–pengeret frame over the saka guru encloses the pamidhangan, the most honoured zone under the roof.',
    specs: ['3 ring frames', 'Tenon joints', 'Teak'],
  },
  {
    id: 'tumpang_sari', cat: 'frame', name: 'Tumpang Sari', alias: 'Tumpangsari', en: 'Stepped beam stack',
    explode: [0, 5.9, 0], anchor: [0, 6.95, 2.6], focusDir: [0.5, -0.55, 1],
    desc: 'Frames of beams stacked on top of the saka guru. Each course steps further out than the one below, forming an upside-down stepped pyramid.',
    fn: 'Cantilevers outward to hold the foot of the steep brunjung rafters, gathering a large roof onto just four columns.',
    meaning: 'The most richly carved and painted part of the house, often gilded (prada) with lung-lungan tendril motifs. The number of courses is traditionally odd and reflects the owner’s rank.',
    specs: ['5 courses', 'Stepped outward', 'Carved & gilded'],
  },
  {
    id: 'dadha_peksi', cat: 'frame', name: 'Dhadha Peksi', alias: 'Dada peksi', en: '“Bird’s chest” beam', interp: true,
    explode: [0, 6.9, 0], anchor: [1.3, 6.6, 0], focusDir: [0.5, -1, 0.9],
    desc: 'A heavy beam across the middle of the tumpang sari, parallel to the blandar, usually carved and painted. Its name means “bird’s chest” in Javanese.',
    fn: 'Stiffens the central frame and splits the space over the saka guru into two halves.',
    meaning: 'The name can be read as a bird’s breast: strong, central and protective, sheltering the heart of the house.',
    specs: ['1 beam', '4.9 m span', 'Painted trim'],
  },
  {
    id: 'uleng', cat: 'frame', name: 'Uleng', alias: 'Plafon', en: 'Recessed stepped ceiling', interp: true,
    explode: [0, 8.3, 0], anchor: [0, 7.95, 0], focusDir: [0.35, -1, 0.7],
    desc: 'The recessed ceiling above the tumpang sari, made of frames stepping inward and upward. You see it when you look straight up from the centre of the pendapa.',
    fn: 'Closes off the middle of the tall roof and draws the eye upward.',
    meaning: 'Its depth marks the sacred centre of the hall, the highest and most honoured place under the roof.',
    specs: ['4 inward steps', 'Ceiling board', 'Painted panels'],
  },
  {
    id: 'lambang_gantung', cat: 'frame', name: 'Lambang Gantung', alias: 'Saka benthung', en: 'Hanging roof-tier posts',
    explode: [0, 7.7, 0], anchor: [-3.25, 6.5, 2.95],
    desc: 'Short hanging posts (saka benthung) and light ring beams at the foot of the steep brunjung. They carry the top of the gentler penanggap roof, leaving a gap between the two tiers.',
    fn: 'Joins two roof tiers of different pitch. The gap between them lets warm air out and daylight in.',
    meaning: 'Joglo are classified by how their roof tiers meet. In the lambang gantung type the tiers are separated by a gap like this one; in the lambangsari type a beam joins them directly, with no gap.',
    specs: ['2 rings + posts', '~0.7 m vent gap'],
  },
  {
    id: 'usuk', cat: 'roof', name: 'Usuk & Reng', alias: 'Usuk, reng', en: 'Rafters & battens', interp: true,
    explode: [0, 9.7, 0], anchor: [4.4, 5.55, 3.9],
    desc: 'Usuk (rafters) run from the upper frames down to the eaves. Thin reng (battens) laid across them hold the clay tiles. In many joglo the corner rafters fan out radially (usuk peniyung) like the ribs of an umbrella; this model simplifies them to parallel rafters.',
    fn: 'Pass the weight of the tiles to the beams and hips, and set the pitch of each roof tier.',
    meaning: 'Many slender members sharing one load, a picture of gotong royong, the Javanese practice of mutual help.',
    specs: ['{rafters} rafters', '{battens} battens'],
  },
  {
    id: 'dudur', cat: 'roof', name: 'Dudur', alias: 'Jurai', en: 'Hip rafters',
    explode: [0, 10.9, 0], anchor: [7.35, 4.15, 6.45],
    desc: 'Heavy diagonal rafters along the four corners of each roof tier, where two slopes meet.',
    fn: 'Carry the ends of the shorter corner rafters and hold the hipped shape of each tier.',
    meaning: 'They give the joglo its sweeping pyramid silhouette.',
    specs: ['12 hips', '3 roof tiers'],
  },
  {
    id: 'molo', cat: 'roof', name: 'Molo', alias: 'Suwunan', en: 'Ridge beam',
    explode: [0, 10.9, 0], anchor: [0, 10.8, 0],
    desc: 'The ridge beam at the very top of the brunjung, where the rafters and hips meet.',
    fn: 'Ties together the tops of the brunjung rafters and dudur.',
    meaning: 'Seen as the head of the house. Lifting it into place is celebrated with the munggah molo ceremony, often with rice, bananas and cloth hung from the beam.',
    specs: ['2.1 m long', 'Highest timber'],
  },
  {
    id: 'atap_brunjung', cat: 'roof', name: 'Atap Brunjung', alias: 'Brunjung', en: 'Upper roof', interp: true,
    explode: [0, 14.4, 0], anchor: [0, 9.2, 1.4], roof: true,
    desc: 'The tall, steep central roof over the saka guru. It is the defining joglo silhouette, with a short ridge and very steep hipped ends.',
    fn: 'Sheds heavy tropical rain quickly, and its tall inner volume lets warm air rise away from people below.',
    meaning: 'A roof like a mountain (gunungan) rising over the sacred centre, joining earth and sky.',
    specs: ['≈52–57° pitch', 'Ridge +11.0 m', 'Clay tiles'],
  },
  {
    id: 'atap_penanggap', cat: 'roof', name: 'Atap Penanggap', alias: 'Penanggap', en: 'Middle roof tier',
    explode: [0, 13.1, 0], anchor: [0, 5.55, 4.3], roof: true,
    desc: 'The second roof tier around the brunjung, at a gentler pitch, resting on the saka penanggap.',
    fn: 'Widens the covered area and protects the inner frame, while the gap above it vents the roof.',
    meaning: 'The change in pitch between tiers gives the joglo its layered, stepped look.',
    specs: ['≈34° pitch', 'Clay tiles'],
  },
  {
    id: 'atap_penitih', cat: 'roof', name: 'Atap Penitih', alias: 'Emper', en: 'Lower veranda roof',
    explode: [0, 12.1, 0], anchor: [0, 4.2, 6.4], roof: true,
    desc: 'The lowest and widest roof tier, at a shallow pitch, overhanging the platform on every side.',
    fn: 'Deep eaves keep sun and slanting rain off the floor and the inner timber.',
    meaning: 'Shelters the edge of the hall where the courtyard and the house meet.',
    specs: ['≈20° pitch', '0.7 m overhang', 'Clay tiles'],
  },
  {
    id: 'mustaka', cat: 'roof', name: 'Wuwungan & Mustaka', alias: 'Bubungan', en: 'Ridge caps & crowns',
    explode: [0, 15.8, 0], anchor: [0.8, 11.9, 0],
    desc: 'Ridge and hip capping tiles (wuwung) that seal the joints between slopes, finished at the ridge ends with ornamental terracotta crowns.',
    fn: 'Keeps rain out of the ridge and hip joints, the weakest points of a tiled roof.',
    meaning: 'The crown is the crowning point of the house. Ridge ornaments were often symbols of protection and prosperity.',
    specs: ['2 crowns', 'Ridge + 12 hip caps', 'Terracotta'],
  },
];
