// Anatomy data for the omah's parts: naming, explode vector, label anchor and learning notes.
// Sources for each claim are tracked in docs/content-review/joglo-pencu.md.

export const CATEGORIES = [
  { id: 'base',     label: { en: 'Foundation & floors', id: 'Fondasi & lantai' }, local: 'Dasar',   color: '#9a948a' },
  { id: 'column',   label: { en: 'Columns', id: 'Tiang' },                      local: 'Saka',    color: '#b27a45' },
  { id: 'frame',    label: { en: 'Frame', id: 'Rangka' },                       local: 'Rangka',  color: '#dcab52' },
  { id: 'walls',    label: { en: 'Walls & doors', id: 'Dinding & pintu' },      local: 'Gebyok',  color: '#d9c7a0' },
  { id: 'interior', label: { en: 'Inner room', id: 'Ruang dalam' },             local: 'Jero',    color: '#b3674a' },
  { id: 'roof',     label: { en: 'Roof', id: 'Atap' },                          local: 'Atap',    color: '#cf5b3f' },
];

export const PARTS = [
  {
    id: 'bebatur', cat: 'base', name: 'Bebatur & Bancik', alias: 'Lantai bertrap', en: { en: 'Plinth, porch and steps', id: 'Bebatur, teras, dan anak tangga' },
    explode: [0, 0, 0], anchor: [3.5, 0.5, 6.9],
    desc: { en: 'A stone plinth with a lower porch (tritisan) in front, reached by steps (bancik) from the yard. In Kudus a house like this is said to be “berbancik dhuwur”: on a high, stepped floor.', id: 'Bebatur batu dengan teras lebih rendah (tritisan) di depan, dicapai dengan anak tangga (bancik) dari halaman. Di Kudus rumah seperti ini disebut “berbancik dhuwur”: berlantai tinggi dan bertrap.' },
    fn: { en: 'Lifts the house off the damp ground. Every step inward is also a step up: yard, porch, jogosatru, dalem, gedongan.', id: 'Mengangkat rumah dari tanah yang lembap. Setiap langkah ke dalam juga langkah naik: halaman, teras, jogosatru, dalem, gedongan.' },
    meaning: { en: 'Floor height marks how private and how honoured each space is. Some accounts link the five levels to the five pillars of Islam.', id: 'Ketinggian lantai menandai seberapa privat dan terhormat setiap ruang. Sebagian tulisan mengaitkan lima tingkat lantai dengan lima rukun Islam.' },
    specs: [{ en: '5 floor levels', id: '5 tingkat lantai' }, { en: 'Porch +0.45 m', id: 'Teras +0,45 m' }, { en: 'Jogosatru +0.70 m', id: 'Jogosatru +0,70 m' }],
  },
  {
    id: 'umpak', cat: 'base', name: 'Umpak', alias: 'Ompak', en: { en: 'Stone column bases', id: 'Alas tiang dari batu' },
    explode: [0, 1.0, 0], anchor: [1.9, 1.5, 1.7], focusDir: [0.8, 0.4, 1],
    desc: { en: 'Stone bases under the columns. Under the soko guru they are tall and rise well above the dalem floor.', id: 'Alas batu di bawah tiang. Di bawah soko guru, umpaknya tinggi dan menjulang di atas lantai dalem.' },
    fn: { en: 'Keep the timber off the ground. The posts rest on the stones rather than being buried, so the frame can be taken apart.', id: 'Menjauhkan kayu dari tanah. Tiang bertumpu di atas batu, tidak ditanam, sehingga rangkanya bisa dibongkar.' },
    meaning: { en: 'On the soko guru the decoration is kept to the umpak at the foot and a flower-like crown at the top; the shaft itself is plain.', id: 'Pada soko guru, hiasan hanya diberikan pada umpak di kaki dan mahkota berbentuk kelopak bunga di ujung atas; batang tiangnya polos.' },
    specs: [{ en: '12 bases', id: '12 umpak' }, { en: 'Tall under the soko guru', id: 'Tinggi di bawah soko guru' }],
  },
  {
    id: 'geladakan', cat: 'base', name: 'Geladakan', alias: 'Lantai gladak', en: { en: 'Raised timber floor of the dalem', id: 'Lantai kayu dalem yang ditinggikan' },
    explode: [0, 0.6, -2.5], anchor: [-4.2, 1.2, 0.4], focusDir: [-0.4, 0.8, 1],
    desc: { en: 'The dalem has a floor of timber boards on joists, raised above the jogosatru like a low platform (panggung).', id: 'Dalem berlantai papan kayu di atas balok-balok, lebih tinggi dari jogosatru seperti panggung rendah.' },
    fn: { en: 'Raises the family’s inner room above the guest hall. You step up onto it through the dalem door.', id: 'Meninggikan ruang dalam keluarga di atas ruang tamu. Kita naik ke atasnya melalui pintu dalem.' },
    meaning: { en: 'Many geladakan have rotted and been replaced with tiled floors at the jogosatru’s level, and the gedongan has often gone with them.', id: 'Banyak geladakan telah lapuk dan diganti lantai ubin setinggi jogosatru, dan gedongan sering ikut hilang bersamanya.' },
    specs: [{ en: 'Floor +1.15 m', id: 'Lantai +1,15 m' }, { en: 'Teak boards', id: 'Papan jati' }],
  },
  {
    id: 'soko_guru', cat: 'column', name: 'Soko Guru', alias: 'Saka guru', en: { en: 'Four master columns', id: 'Empat tiang utama' },
    explode: [0, 2.2, 0], anchor: [1.9, 3.9, 1.7], focusDir: [0.9, 0.25, 1],
    desc: { en: 'Four teak columns in the middle of the dalem that carry the rong-rongan and the tall pencu roof above it.', id: 'Empat tiang jati di tengah dalem yang memikul rong-rongan dan atap pencu yang tinggi di atasnya.' },
    fn: { en: 'The main load path of the house: the pencu’s weight comes down through these four posts.', id: 'Jalur beban utama rumah: berat atap pencu disalurkan turun melalui keempat tiang ini.' },
    meaning: { en: 'The four soko guru and the rong-rongan they carry are the structural core of every pencu house.', id: 'Empat soko guru dan rong-rongan yang dipikulnya adalah inti struktur setiap rumah pencu.' },
    specs: [{ en: '4 columns', id: '4 tiang' }, '30 × 30 cm', { en: 'Plain shaft', id: 'Batang polos' }],
  },
  {
    id: 'saka', cat: 'column', name: 'Saka Pengapit', alias: 'Tiang gebyok', en: { en: 'Wall and door columns', id: 'Tiang dinding dan pintu' },
    explode: [0, 1.8, 0.8], anchor: [-2.5, 2.6, 5.4],
    desc: { en: 'Columns that frame each gebyok unit. Each unit of the front wall stands between two columns, and the dalem door is flanked by a heavier pair.', id: 'Tiang-tiang yang membingkai setiap unit gebyok. Setiap unit dinding depan berdiri di antara dua tiang, dan pintu dalem diapit sepasang tiang yang lebih besar.' },
    fn: { en: 'Hold the gebyok panels and carry the ring beams and konsol brackets.', id: 'Menahan panel gebyok serta memikul balok keliling dan konsol.' },
    meaning: { en: 'Carved columns beside the gebyok and doors are among the decorations that are part of the structure itself.', id: 'Tiang berukir di samping gebyok dan pintu termasuk hiasan yang menyatu dengan strukturnya.' },
    specs: [{ en: '18 columns', id: '18 tiang' }],
  },
  {
    id: 'tiang_tunggal', cat: 'column', name: 'Tiang Tunggal', alias: 'Tiang tunggal', en: { en: 'Single post at the dalem door', id: 'Tiang tunggal di pintu dalem' },
    explode: [0, 1.4, 1.2], anchor: [-0.92, 2.2, 3.4], focusDir: [-0.3, 0.2, 1],
    desc: { en: 'A lone post standing in the jogosatru in front of one of the columns that flank the dalem door.', id: 'Sebuah tiang yang berdiri sendiri di jogosatru, di depan salah satu tiang pengapit pintu dalem.' },
    fn: { en: 'Props the end of the large konsol above the door.', id: 'Menopang ujung konsol besar di atas pintu.' },
    meaning: { en: 'It breaks the symmetry of the door on purpose, one of the details that set the Kudus house apart.', id: 'Tiang ini sengaja memecah kesimetrisan pintu, salah satu detail yang membedakan rumah Kudus.' }, interp: true,
    specs: [{ en: '1 post', id: '1 tiang' }, { en: 'Left of the door', id: 'Di kiri pintu' }],
  },
  {
    id: 'blandar', cat: 'frame', name: 'Blandar', alias: 'Belandar', en: { en: 'Ring and eave beams', id: 'Balok keliling dan balok tritisan' },
    explode: [0, 3.4, 0], anchor: [6.0, 3.85, 0], focusDir: [1, 0.2, 0.3],
    desc: { en: 'The ring beam on top of the outer walls, the heavy beam over the gebyok dalem and the eave beams of the front and back tritisan.', id: 'Balok keliling di atas dinding luar, balok besar di atas gebyok dalem, dan balok tritisan depan dan belakang.' },
    fn: { en: 'Collect the weight of the penanggap and tritisan roofs and pass it to the columns and walls.', id: 'Mengumpulkan beban atap penanggap dan tritisan lalu menyalurkannya ke tiang dan dinding.' },
    meaning: { en: 'The beam over the dalem door is part of the composition guests are meant to admire, with the door, its columns and konsol.', id: 'Balok di atas pintu dalem adalah bagian dari komposisi yang memang untuk dikagumi tamu, bersama pintu, tiang, dan konsolnya.' },
    specs: [{ en: 'Teak', id: 'Jati' }, { en: 'Pegged joints', id: 'Sambungan pasak' }],
  },
  {
    id: 'konsol', cat: 'frame', name: 'Konsol', alias: 'Kerbil', en: { en: 'Brackets', id: 'Penyangga siku' },
    explode: [0, 1.6, 1.6], anchor: [4.25, 2.95, 6.3], focusDir: [0.4, -0.3, 1],
    desc: { en: 'Timber brackets that reach out from the columns. A row along the front carries the tritisan, and a big pair at the dalem door carries its beam. They may be almost plain, or carved as an elephant’s head (konsol gajahan).', id: 'Siku kayu yang menjorok dari tiang. Sederet di depan memikul tritisan, dan sepasang yang besar di pintu dalem memikul baloknya. Bentuknya bisa nyaris polos, atau diukir menyerupai kepala gajah (konsol gajahan).' },
    fn: { en: 'Let the eaves overhang without posts at the edge of the porch.', id: 'Memungkinkan tritisan menjorok tanpa tiang di tepi teras.' },
    meaning: { en: 'Brackets of this kind are one of the marks of north-coast Javanese houses such as Kudus.', id: 'Konsol seperti ini adalah salah satu ciri rumah pesisir utara Jawa seperti Kudus.' },
    specs: [{ en: '15 brackets', id: '15 konsol' }],
  },
  {
    id: 'rong_rongan', cat: 'frame', name: 'Rong-rongan', alias: 'Tumpang sari & luweng', en: { en: 'Stepped frame over the soko guru', id: 'Rangka bertingkat di atas soko guru' },
    explode: [0, 4.6, 0], anchor: [0, 6.6, 2.1], focusDir: [0.5, -0.6, 1],
    desc: { en: 'The space framed by the soko guru and the beams on top of them. Courses of tumpang sari step outward, then the luweng steps back inward up to a ceiling board. Almost every surface is carved, except the soko guru themselves.', id: 'Ruang yang dibingkai soko guru dan balok-balok di atasnya. Susunan tumpang sari berundak ke luar, lalu luweng berundak kembali ke dalam hingga papan langit-langit. Hampir seluruh permukaannya diukir, kecuali soko guru itu sendiri.' },
    fn: { en: 'Gathers the steep pencu roof onto just four columns.', id: 'Menghimpun atap pencu yang curam di atas empat tiang saja.' },
    meaning: { en: 'In the joglo of southern Central Java the outward tumpang sari often has more courses than the luweng. In Kudus it is the other way round: the luweng has more.', id: 'Pada joglo di Jawa Tengah bagian selatan, tumpang sari ke luar sering lebih banyak susunnya daripada luweng. Di Kudus justru sebaliknya: luweng-nya yang lebih banyak.' },
    specs: [{ en: '3 courses out', id: '3 susun ke luar' }, { en: '7 courses in (luweng)', id: '7 susun ke dalam (luweng)' }, { en: 'Carved', id: 'Berukir' }],
  },
  {
    id: 'gebyok_jogosatru', cat: 'walls', name: 'Gebyok Jogosatru', alias: 'Gebyok depan', en: { en: 'Carved front wall', id: 'Dinding depan berukir' },
    explode: [0, 0.4, 2.6], anchor: [-5.1, 2.3, 5.5], focusDir: [0, 0.15, 1],
    desc: { en: 'The timber front wall, in the standard Kudus pattern: two rows of panels between three horizontal bands, with the upper row and bands carved. In the middle is a double door that opens like a butterfly (pintu kupu tarung), with a sliding gebyok (gebyok geser) on either side.', id: 'Dinding depan dari kayu dengan pola baku Kudus: dua baris panel di antara tiga bidang mendatar, dengan baris atas dan bidang mendatarnya diukir. Di tengahnya ada pintu ganda yang membuka seperti sayap kupu-kupu (pintu kupu tarung), diapit gebyok geser di kedua sisinya.' },
    fn: { en: 'Closes the jogosatru, the room where guests are received. The sliding gebyok open the front wide for gatherings.', id: 'Menutup jogosatru, ruang tempat tamu diterima. Gebyok geser dapat membuka bagian depan lebar-lebar untuk pertemuan.' },
    meaning: { en: 'A central door is Javanese; doubled side openings (a sliding gebyok inside, a kere outside) are particular to Kudus. The outer face is carved, the inner face is left plain.', id: 'Pintu utama di tengah adalah ciri rumah Jawa; bukaan samping yang berlapis (gebyok geser di dalam, kere di luar) adalah kekhasan Kudus. Sisi luarnya diukir, sisi dalamnya dibiarkan polos.' },
    specs: [{ en: 'Kupu tarung door', id: 'Pintu kupu tarung' }, { en: '2 gebyok geser', id: '2 gebyok geser' }, { en: '5 panels per row', id: '5 panel per baris' }],
  },
  {
    id: 'kere', cat: 'walls', name: 'Kere', alias: 'Kerei, pintu sorong', en: { en: 'Lattice screens', id: 'Pintu kisi-kisi' },
    explode: [0, 0.4, 3.6], anchor: [1.725, 2.4, 5.6], focusDir: [0.2, 0.1, 1],
    desc: { en: 'Light screens about 1.5 m high, hung from the beam in front of the sliding gebyok: carved bands at the top, middle and bottom joined by thin vertical bars.', id: 'Kisi-kisi ringan setinggi sekitar 1,5 m yang digantung pada balok di depan gebyok geser: bidang berukir di atas, tengah, dan bawah yang disambung jeruji tegak yang tipis.' },
    fn: { en: 'With the gebyok slid open, the kere lets in air and light while screening the jogosatru from the yard.', id: 'Saat gebyok geser dibuka, kere memasukkan udara dan cahaya sambil menyaring pandangan dari halaman ke jogosatru.' },
    meaning: { en: 'Its bands carry motifs such as patran, lung-lungan and an interlaced swastika, a motif older than Islam in Java.', id: 'Bidang-bidangnya memuat motif seperti patran, lung-lungan, dan jalinan swastika, motif yang lebih tua dari Islam di Jawa.' },
    specs: [{ en: '2 screens', id: '2 kere' }, { en: '≈1.5 m high', id: 'Tinggi ≈1,5 m' }],
  },
  {
    id: 'tembok', cat: 'walls', name: 'Tembok', alias: 'Dinding samping & belakang', en: { en: 'Side and back walls', id: 'Dinding samping dan belakang' },
    explode: [0, 0.6, -1.6], anchor: [6.1, 2.4, -2.6], focusDir: [1, 0.2, 0.2],
    desc: { en: 'Plastered masonry walls on the sides and back, with a side door to the pawon.', id: 'Dinding tembok berplester di samping dan belakang, dengan pintu samping menuju pawon.' },
    fn: { en: 'Enclose the house on the three sides that guests do not see.', id: 'Menutup rumah di tiga sisi yang tidak dilihat tamu.' },
    meaning: { en: 'In a survey of 55 pencu houses, most had a timber front and masonry sides and back. Only the grandest were timber all round.', id: 'Dalam survei terhadap 55 rumah pencu, kebanyakan berdinding depan kayu dengan samping dan belakang dari tembok. Hanya yang paling megah yang seluruhnya dari kayu.' },
    specs: [{ en: 'Masonry', id: 'Tembok bata' }, { en: '1 side door', id: '1 pintu samping' }],
  },
  {
    id: 'gebyok_dalem', cat: 'walls', name: 'Gebyok Dalem', alias: 'Gebyok jero', en: { en: 'Carved wall of the dalem', id: 'Dinding dalem berukir' },
    explode: [0, 0.8, 1.6], anchor: [-4.75, 2.6, 2.85], focusDir: [-0.2, 0.15, 1],
    desc: { en: 'The wall between the jogosatru and the dalem: four gebyok units and a large central door, raised on the dalem floor and reached by a bancik step. The pattern repeats the front wall’s, but finer and more richly carved, sometimes with gold leaf behind the openwork.', id: 'Dinding antara jogosatru dan dalem: empat unit gebyok dan pintu besar di tengah, berdiri di atas lantai dalem yang lebih tinggi dan dicapai dengan anak tangga (bancik). Polanya mengulang dinding depan, tetapi lebih halus dan lebih kaya ukiran, kadang dengan kertas emas di balik ukiran tembusnya.' },
    fn: { en: 'Separates the guests’ room from the family’s.', id: 'Memisahkan ruang tamu dari ruang keluarga.' },
    meaning: { en: 'It is what guests sit facing in the jogosatru. It is also the piece most often sold off and reused in new buildings.', id: 'Dinding inilah yang dihadapi tamu saat duduk di jogosatru. Ia juga bagian yang paling sering dijual dan dipakai ulang di bangunan baru.' },
    specs: [{ en: '4 units + door', id: '4 unit + pintu' }, { en: 'Gilded panels', id: 'Panel berprada' }],
  },
  {
    id: 'gedongan', cat: 'interior', name: 'Gedongan', alias: 'Gedhongan', en: { en: 'The inner room', id: 'Ruang terdalam' },
    explode: [0, 1.4, -2.4], anchor: [-1.6, 2.6, -2.5], focusDir: [-0.2, 0.2, 1],
    desc: { en: 'A room at the back of the dalem, behind the rong-rongan. Its front is a sliding kupu tarung door between two gebyok units, under a large openwork crest (jenggeran).', id: 'Sebuah bilik di bagian belakang dalem, di belakang rong-rongan. Bagian depannya berupa pintu kupu tarung geser di antara dua unit gebyok, di bawah hiasan jenggeran besar berukir tembus.' },
    fn: { en: 'Where the parents slept and kept the household’s valuables. By tradition it was also the bridal chamber on the wedding night.', id: 'Tempat orang tua tidur dan menyimpan harta benda. Menurut tradisi, ia juga menjadi kamar pengantin pada malam pertama.' },
    meaning: { en: 'The innermost, highest and most sacred room of the house, and the most richly carved.', id: 'Ruang terdalam, tertinggi, dan paling sakral di rumah, sekaligus yang paling kaya ukiran.' },
    specs: [{ en: 'Floor +1.35 m', id: 'Lantai +1,35 m' }, { en: 'Sliding door', id: 'Pintu geser' }, 'Jenggeran'],
  },
  {
    id: 'usuk', cat: 'roof', name: 'Usuk, Dudur & Molo', alias: 'Rangka atap', en: { en: 'Rafters, hips and ridge', id: 'Usuk, jurai, dan bubungan' },
    explode: [0, 7.4, 0], anchor: [4.4, 4.8, 3.9],
    desc: { en: 'Rafters and battens of every roof tier, the hip rafters at the corners and the short molo ridge beam at the top of the pencu.', id: 'Usuk dan reng setiap susun atap, jurai di sudut-sudutnya, dan balok bubungan molo yang pendek di puncak pencu.' },
    fn: { en: 'Carry the clay tiles and set the pitch of each tier.', id: 'Memikul genteng dan menentukan kemiringan setiap susun.' },
    meaning: { en: 'Like the rest of the frame, the roof is jointed timber that can be taken down and put up again.', id: 'Seperti rangka lainnya, atap ini tersusun dari kayu bersambung yang dapat dibongkar dan dipasang kembali.' },
    specs: [{ en: '{rafters} rafters', id: '{rafters} usuk' }, { en: '{battens} battens', id: '{battens} reng' }],
  },
  {
    id: 'atap_pencu', cat: 'roof', name: 'Atap Pencu', alias: 'Brunjung', en: { en: 'The tall central roof', id: 'Atap tengah yang menjulang' }, roof: true,
    explode: [0, 11.6, 0], anchor: [0, 9.2, 1.1],
    desc: { en: 'The steep upper roof over the soko guru, taller and more pointed than in most joglo. It gives the house its name: pencu means rising to a peak, and is also the word for the raised boss in the middle of a gong.', id: 'Atap atas yang curam di atas soko guru, lebih tinggi dan lebih runcing daripada kebanyakan joglo. Dari atap inilah rumah ini dinamai: pencu berarti memuncak atau menjulang, dan juga sebutan untuk tonjolan di tengah gong.' },
    fn: { en: 'Throws off heavy rain and gives the dalem a tall, airy space under the roof.', id: 'Membuang air hujan yang deras dengan cepat dan memberi dalem ruang yang tinggi dan lapang di bawah atap.' },
    meaning: { en: 'Because the roof is so tall, the walls look short and horizontal; the high floor lifts them back up.', id: 'Karena atapnya begitu tinggi, dindingnya tampak pendek dan mendatar; lantai yang tinggi mengangkatnya kembali.' },
    specs: [{ en: '≈61° pitch', id: 'Kemiringan ≈61°' }, { en: 'Ridge +11.4 m', id: 'Bubungan +11,4 m' }, { en: 'Clay tiles', id: 'Genteng tanah liat' }],
  },
  {
    id: 'atap_penanggap', cat: 'roof', name: 'Atap Penanggap', alias: 'Penanggap', en: { en: 'Main roof tier', id: 'Susun atap utama' }, roof: true,
    explode: [0, 9.6, 0], anchor: [-4.6, 4.9, 3.6],
    desc: { en: 'The broad hipped tier around the pencu that covers the whole house, jogosatru and dalem alike.', id: 'Susun atap limasan yang lebar di sekeliling pencu, menaungi seluruh rumah, baik jogosatru maupun dalem.' },
    fn: { en: 'Shelters the walls and rooms with eaves on all four sides.', id: 'Menaungi dinding dan ruang dengan tritisan di keempat sisi.' },
    meaning: { en: 'Its gentler slope sets off the steep pencu rising out of it.', id: 'Kemiringannya yang lebih landai menonjolkan pencu curam yang menjulang darinya.' },
    specs: [{ en: '≈36° pitch', id: 'Kemiringan ≈36°' }, { en: 'Clay tiles', id: 'Genteng tanah liat' }],
  },
  {
    id: 'tritisan', cat: 'roof', name: 'Tritisan', alias: 'Emper', en: { en: 'Front and back eaves', id: 'Tritisan depan dan belakang' }, roof: true,
    explode: [0, 8.2, 0], anchor: [-4.2, 3.6, 6.8],
    desc: { en: 'Low, shallow roofs at the front and back, carried on konsol brackets. The one at the front shelters the porch, which is also called the tritisan.', id: 'Atap rendah dan landai di depan dan belakang, dipikul konsol. Tritisan depan meneduhi teras, yang juga disebut tritisan.' },
    fn: { en: 'Keep sun and rain off the carved front wall and the porch.', id: 'Melindungi dinding depan yang berukir dan teras dari terik dan hujan.' },
    meaning: { en: 'The porch under it is the first covered step from the yard into the house.', id: 'Teras di bawahnya adalah langkah beratap pertama dari halaman ke dalam rumah.' },
    specs: [{ en: '2 tritisan', id: '2 tritisan' }, { en: '≈16° pitch', id: 'Kemiringan ≈16°' }],
  },
  {
    id: 'gendheng', cat: 'roof', name: 'Gendheng Wuwung', alias: 'Gunungan, wayang, kodok', en: { en: 'Ornamental ridge tiles', id: 'Genteng hias bubungan' },
    explode: [0, 13.2, 0], anchor: [0, 12.2, 0.2],
    desc: { en: 'Terracotta tiles along the ridge and hips. A gunungan sits in the middle of the ridge between two wayang tiles; small kodok (frog) tiles run down each hip and end in another wayang. They are sometimes set with fragments of blue-and-white porcelain.', id: 'Genteng terakota di sepanjang bubungan dan jurai. Sebuah gunungan duduk di tengah bubungan di antara dua genteng wayang; genteng kodok kecil berderet di setiap jurai dan berakhir dengan genteng wayang. Kadang ditempeli pecahan porselen biru-putih.' },
    fn: { en: 'Seal the joints of the roof and crown the house.', id: 'Menutup sambungan atap dan memahkotai rumah.' },
    meaning: { en: 'One reading of the crown: a reminder that people must seek the protection of God.', id: 'Salah satu tafsir atas mahkota ini: pengingat bahwa manusia wajib berlindung dan memohon perlindungan kepada Allah.' },
    specs: ['1 gunungan', { en: '10 wayang tiles', id: '10 genteng wayang' }, { en: 'Terracotta', id: 'Terakota' }],
  },
];
